spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        stack.auto: false
        region.static: ap-northeast-2
        credentials:
          accessKey: ${S3_ACCESS_KEY}
          secretKey: ${S3_SECRET_ACCESS_KEY}

  error:
    printStackTrace: true


  servlet:
    multipart:
      max-file-size: 500MB

server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
    use-relative-redirects: true

# LiveKit configuration
livekit:
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}

#naver-ocr
ocr:
  api:
    url: ${OCR_API_URL}
    key: ${OCR_SECRET_KEY}
    format: png
    version: V1
    imageName: demo



